### ISSUE TITLE
Правки в посадочной странице

### ISSUE THREAD

**Issue by aChudinov** [shriming/chat#107]
Поправить ошибки из #103 
- [x] Убрать опечатки в тексте
- [x] Поправить пути к картинкам
- [x] Убрать блок scrillbox
- [x] Убрать local.js из

**Comment by BorodinDK** [comment]
- [ ] Убрать опечатки в тексте
- [ ] Поправить пути к картинкам
- [ ] Убрать local.js из

**Comment by aChudinov** [comment]
@BorodinDK Создавай пуллреквест, по-моему все в порядке
