### ISSUE TITLE
Автоматический выбор канала при входе

### ISSUE THREAD

**Issue by mkholodnyak** [shriming/chat#109]
По дефолту пользователь должен заходить в чат `general`.

**Comment by aChudinov** [comment]
А если переименуем general?

**Comment by mkholodnyak** [comment]
Можно просто первый из списка выбирать

**Comment by aChudinov** [comment]
Надо еще посмотреть что возваращает `channels.list`, вдруг там есть какое-нибудь поле последнего сообщения, тогда можно выбирать его. Если нет, то дженерал, если дженерала нет, то первое из списка

**Comment by BorodinDK** [comment]
в channels.list нет

**Comment by Borodin** [comment]
Теперь канал открывается по хэш-ссылке, если ее нет, открывается general, даже если он был переименован.

**Comment by aChudinov** [comment]
@Borodin см комменты в коммите
