### ISSUE TITLE
Выбрать 20 emoji-иконок 

### ISSUE THREAD

**Issue by mkholodnyak** [shriming/chat#131]
Нужно выбрать 20 лучших иконок для чата.

Обсуждаем :)

**Comment by mkholodnyak** [comment]
Предлагаю:
- :+1:
- :ok_hand:
- :disappointed:
- :fire:
- :grinning:
- :bomb:
- :hankey:

**Comment by aChudinov** [comment]
Какашку главное не забыть, да! :hankey:

**Comment by Borodin** [comment]
### Top 10 Emoji
1. :stuck_out_tongue_winking_eye: 
2. :pray: 
3. :full_moon_with_face: 
4. :kissing_heart: 
5. :+1: 
6. :hankey: 
7. :joy: 
8. :heart_eyes: 
9. :new_moon_with_face: 
10. :sweet_potato: 

---

:dancers: :chicken: :goat: :cake: :clap:

**Comment by Yeti-or** [comment]
а объясните ещё раз почему не взять все?

**Comment by mkholodnyak** [comment]
Хероку плохо становилось, но уже решили.
