### ISSUE TITLE
Сделать вёрстку адаптивной

### ISSUE THREAD

**Issue by BorodinDK** [shriming/chat#136]

**Comment by BorodinDK** [comment]
![screencapture-192-168-0-51-1337-1444663514356](https://cloud.githubusercontent.com/assets/4511390/10431601/a5cff812-710e-11e5-979a-9ec85c68c220.png)
![screencapture-192-168-0-51-1337-1444663504749](https://cloud.githubusercontent.com/assets/4511390/10431603/a89fbabe-710e-11e5-8bf8-a00cf1547ae6.png)

**Comment by aChudinov** [comment]
Круто!

**Comment by aChudinov** [comment]
@BorodinDK Денис, а может пораньше сделаем мобильник? Там просто до этого совсем криво выглядит
![image](https://cloud.githubusercontent.com/assets/6690086/10433703/bd98eb26-711c-11e5-9784-a5011dd5630f.png)

**Comment by BorodinDK** [comment]
В переменных [variables.styl](https://github.com/shriming/chat/blob/feat/touch/frontend/common.blocks/variables/variables.styl) Это можно задать, к примеру 600px по ширине место 400px пойдёт?

**Comment by aChudinov** [comment]
Я думаю да, получше будет

**Comment by mkholodnyak** [comment]
@BorodinDK стили под телефон можно на уровне touch доопределять. Но это требует немного дополнительного кода на серверной стороне.

**Comment by BorodinDK** [comment]
@mkholodnyak Я так сначала и начал делать, а потом всё переделал в common.block
ибо понял что в многих местах код продублируется

**Comment by BorodinDK** [comment]
@mkholodnyak как бы ты сделал? Сделал бы определения мобильного устройства на сервере, а потом решал бы подключать touch.block или нет?

**Comment by mkholodnyak** [comment]
Ага, Сергей говорил, что так в серпе Яндекса делают
