### ISSUE TITLE
Добавить анимацию 

### ISSUE THREAD

**Issue by mkholodnyak** [shriming/chat#149]
- [ ] Анимация появления сообщений
- [ ] Анимация появления инпута для добавления канала
- [ ] Анимация появления скриншота на лендинге

**Comment by BorodinDK** [comment]
Как ты хочешь анимировать скриншот?

**Comment by aChudinov** [comment]
Чтобы справа выползал, можно еще с баунсом каким-нибудь

**Comment by mkholodnyak** [comment]
Closed via #161.
