### ISSUE TITLE
Интеграция с Slack API

### ISSUE THREAD

**Issue by aChudinov** [shriming/chat#15]
- [x] Передача username в сообщениях
- [x] Определение схемы взаимодействия с API Slack: RTM, Web API
- [x] Безопасность запросов через Web API
- [x] Добавить проверку на успешный init для slack api. Сейчас, если юзер не залогинен в slack,
  то приложение падает с ошибкой `error: Sending 500 ("Server Error") response: 
  TypeError: Object #<Object> has no method 'api'
  at Object.module.exports.api (/home/maxim/chat/api/controllers/SlackController.js:17:15)`

**Comment by aChudinov** [comment]
#6

**Comment by mkholodnyak** [comment]
Декомпозировали на две подзадачи ( #23  и #24 )
