### ISSUE TITLE
Вёрстка

### ISSUE THREAD

**Issue by BorodinDK** [shriming/chat#16]
- [x] Layout
  - [x] **Шапка**
    - [x] Логотип
    - [x] Профиль 
      - [x] Имя
      - [x] Аватарка
    - [x] ~~Настройки (иконка)~~
  - [x] **Левый список контактов**
    - [x] ~~Поиск~~
    - [x] Потоки
    - [x] Диалоги
  - [x] **Диалог**
    - [x] Шапка диалога
    - [x] История сообщений
      - [x] Сообщение
    - [x] Инпут

**Comment by mkholodnyak** [comment]
Взял аватарку

**Comment by BorodinDK** [comment]
- [ ] Поправить оцентровку логотипа в шапке
- [ ] Заменить favicon на прозрачный

**Comment by aChudinov** [comment]
@BorodinDK Создавай отдельные таски и закрывай пуллреквестами
