### ISSUE TITLE
Модуль Slack Web API на клиенте

### ISSUE THREAD

**Issue by aChudinov** [shriming/chat#27]
- [x] Базовая реализация
- [x] Передача в каждом запросе CSRF-токена
  
  ~~Декорирование вызовов с помощью debounce~~ - нет возможности обернуть в debounce из bem-core функцию, которая возвращает промис. Если появится необходимость в дальнейшем - надо будет искать возможности реализации.

**Comment by aChudinov** [comment]
#6

**Comment by choudalex** [comment]
dae4c55
