### ISSUE TITLE
Почистить репозиторий от лишних файлов

### ISSUE THREAD

**Issue by mkholodnyak** [shriming/chat#37]
- [x] Убрать лишние файлы из `master`
  - [x] pid.txt
  - [x] Лишние файлы в .gitignore
  - [x] Makefile
  - [x] Убить мёртвые ветки

**Comment by georg-malahov** [comment]
@mkholodnyak Если мы решили удалить Makefile, то нужно тогда и папки `seeds.disable` и `test` удалить из корня, так как с помощью этого файлы мы могли запускать тесты для api/controllers, для которых все необходимое в этих папках лежит.

Кроме того, если удаляем Procfile, то нужно что-то адекватное написать в package.json в script start, чтобы `npm start` запускало наше приложение на heroku. Подробнее [тут](https://devcenter.heroku.com/articles/nodejs-support#default-web-process-type). Я предлагаю Procfile оставить, но подумать над его содержимым, чтобы приложение запускалось быстрее.

**Comment by mkholodnyak** [comment]
#53
