### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by georg-malahov** [shriming/chat#4]
## Api для интеграций (**Research!**)
- Telegram
- Slack
- Hangouts
### Features
- **Авторизация**
  - **Через соц сети**
    - **GitHub**
    - Vk
    - FB
- Чат
  - **Минимум 1 комната, где сидят все**
  - **Авторизация (граватар, действие)**
  - **История сообщений**
    - Через сторонние сервисы и api других сервисов
  - **Ввод сообщений**
    - Кастомные клавиатуры
      - Отправка файлов
      - Редактирование
    - Сгорающие сообщения
  - **Рендеринг сообщений** в зависимости от типа сообщения (ссылки на сервисы, упоминание, группы, людей)
    - **Поддержка markdown (форматирование)**
    - **Многосрочный ввод**
    - **Hot Keys**
  - Настройки (кастомизирование под каждого пользователя, если нужно)
    - Темы для всего чата, каналов и тд.
    - Avatar и Gravatar сервисы
  - Каналы
  - Приватные сообщения
  - Смайлики и стикеры
  - Отправка файлов
  - Боты
    - Боты-помощники
    - Уведомление от других сервисов
  - интеграция с другими сервисами [https://ifttt.com](https://ifttt.com/recipes))
  - История и поиск
  - Сгорающие сообщения
  - Расширения для браузера (уведомления, непрочитанные сообщения)
  - Push-уведомления
  - Работа с сообщениями
    - Редактирование
    - Лайки
    - Реакции на сообщения
- Звонки
  - Звук
  - Видео
  - Шаринг экрана
- Наличие десктоп приложенией
- Консольный клиент
- Коллаборативность
  - Текст
  - Картинки

**Comment by mkholodnyak** [comment]
Перенёс в [wiki](https://github.com/shriming/chat/wiki/Features).
