### ISSUE TITLE
Починить баг авторизации.

### ISSUE THREAD

**Issue by georg-malahov** [shriming/chat#42]
Проблема в inite slack, если юзера и его паспорта нет в базе. Файлы:
`см. /api/services/passport.js и /api/services/slack.js`.

**Comment by georg-malahov** [comment]
@mkholodnyak Если ты уже начал что-то делать по этой задаче, отпишись, пожалуйста.

**Comment by mkholodnyak** [comment]
@yuriMalakhov просто добавить создание сервиса Слэка после авторизации нужно было.

**Comment by georg-malahov** [comment]
@mkholodnyak Ты прав. Сделал примерно тоже, только добавил больше обработчиков. Инициализацию слека делаю, если юзер уже существует и авторизован через слек, и есть accessToken.
