### ISSUE TITLE
Инфраструктура

### ISSUE THREAD

**Issue by georg-malahov** [shriming/chat#5]
- Cборка
  - [x] Добавить linters в Gulp
- Редакторы
  - [x] Добавить editorconfig в репозиторий. Убедиться, что все его поставили и установили в своих редакторах
- Git-hooks
  - [x]  Добавить linters в Pre-commit
- Тесты
  -  \* [x] Серверные тесты
- Travis CI
  - \* [x] Проверка feature branch в Travis при pull request
- Heroku
  - [x] Автоматический деплой master ветки с предварительной проверкой в Travis Ci
  - [x] Поднятие инстанса приложения c feature branch
- Общее
  -  \* [x] Добавить в README.MD инструкцию по install
  -  \* [x] Globals на проект
  - \*  [x] function без пробела 
  - \*  [x] Исправить все файлы в соответствии с jscs

**Comment by aChudinov** [comment]
Что по этой задаче? Надо закрыть?

**Comment by georg-malahov** [comment]
Ни одного теста не написали и не проверили еще) Давай закроем, если что не так, то потом веренем.
