### ISSUE TITLE
Создать блок avatar

### ISSUE THREAD

**Issue by mkholodnyak** [shriming/chat#56]
-  [ ] Создать блок avatar

**Comment by georg-malahov** [comment]
@mkholodnyak Аватарка по логике – это часть блока user. Поэтоу у нас есть блок user с элементом avatar и уже даже отображает фото. Думаю, что нет смысла создавать отдельный блок. Предлагаю этот issue закрыть.
![См. скрин](https://cloud.githubusercontent.com/assets/2431976/10122039/fbf2c1ba-6511-11e5-9964-aca4b8cbaf01.png)

**Comment by mkholodnyak** [comment]
@yuriMalakhov Потом не будет сложностей с реализацией блока сообщения чата?
![screen shot 2015-09-27 at 16 41 54](https://cloud.githubusercontent.com/assets/2128627/10123081/c643ee16-6536-11e5-9ca1-76b6717db45d.png)

**Comment by aChudinov** [comment]
@mkholodnyak Закрываем задачу?

**Comment by mkholodnyak** [comment]
@aChudinov :ok_hand:
