### ISSUE TITLE
Починить приложение на heroku.

### ISSUE THREAD

**Issue by georg-malahov** [shriming/chat#58]
@mkholodnyak После твоего вчерашнего merge в master, у нас поломалось приложение. При этом приложение для твоего pull-request тоже не поднялось. Давайте не будем мержить заведомо поломанные pull-requests, ведь для этого у нас и поднимаются отдельные review apps для каждого реквеста?

**Comment by dima716** [comment]
Нужно разобраться почему borshik ломает стили.

**Comment by mkholodnyak** [comment]
Closed via #60
