### ISSUE TITLE
Индикация загрузки

### ISSUE THREAD

**Issue by aChudinov** [shriming/chat#68]
- [x] Создать блок `loader` для индикации ожидания ответов при загрузке данных
- [x] Реализация js всех элементов блока `dialog` в одном файле
- [x] Добавление бота в коллекцию пользователей в блоке `i-users`

**Comment by mkholodnyak** [comment]
Предлагаю за основу [стандартный компонент](https://ru.bem.info/libs/bem-components/v2.3.0/desktop/spin/)
