### ISSUE TITLE
Дизайн

### ISSUE THREAD

**Issue by Borodin** [shriming/chat#7]
- [x] Список контактов
- [x] Сообщения
- [x] Авторизация (Спеш)
- [ ] Многострочные сообщения
- [ ] Настройки (зависят от настроек)
- [x] Звонки
- [x] Иконка (favicon)
- [x] Информация о пользователе
- [x] Поиск

**Comment by BorodinDK** [comment]
![bem](https://cloud.githubusercontent.com/assets/4511390/9832737/ed21d102-598c-11e5-8064-c0c540bd730b.png)

**Comment by mkholodnyak** [comment]
@BorodinDK а можешь скинуть psd-макет последней версии дизайна?

**Comment by BorodinDK** [comment]
@mkholodnyak скинул https://shri15.slack.com/archives/team-shriming/p1442236864000195

**Comment by Borodin** [comment]
# Новый дизайн

#### **[Скачать PSD макет](https://files.slack.com/files-pri/T0A93M67M-F0AMYK8BX/shriming.psd)**

#### SPLASH PAGE

![2](https://cloud.githubusercontent.com/assets/645491/9880992/be16396a-5bd6-11e5-8272-5db7167b2e17.png)
Это рыба, ее надо будет заменить

#### APP PAGE

![1](https://cloud.githubusercontent.com/assets/645491/9884938/348323ec-5beb-11e5-92e7-06e65488acc7.png)
В макете есть нарисованные попапы на скрытых слоях.

#### VIDEO SCREEN

![3](https://cloud.githubusercontent.com/assets/645491/9881000/c8599282-5bd6-11e5-96af-030cec3fdc91.png)

**Comment by Borodin** [comment]
Основные цвета, переменные стилуса:

```
//User status
user_status_online_color = #69e243
user_status_offline_color = #aaaaaa
user_new_message_color = #f66956

//Call btn
call_on_btn_color = #69e243
call_off_btn_color = #f66956

//Layout
border_color = #efefef
bg_header_color = #383455
bg_bar_color = #efefef

//Text
black_text_color = #111111
gray_text_color = #666666
light_text_color = #aaaaaa
```

### **[Скачать SVG иконки](https://files.slack.com/files-pri/T0A93M67M-F0B048EBG/download/svg.zip)**

**Comment by mkholodnyak** [comment]
Вынесли в [отдельный репозиторий](https://github.com/shriming/Design).
