### ISSUE TITLE
Посадочная страница для неавторизованного пользователя

### ISSUE THREAD

**Issue by aChudinov** [shriming/chat#83]
![2](https://cloud.githubusercontent.com/assets/645491/9880992/be16396a-5bd6-11e5-8272-5db7167b2e17.png)

**Comment by BorodinDK** [comment]
- [x] Изменить иконку в кнопке на векторную
- [x] Убрать баг с большим левым отступом
- [x] Переписать текст
- [x] Сделать все внешние ссылки target: _blank

**Comment by aChudinov** [comment]
@BorodinDK Поправлю! А что за баг с левым отступом? Какой он должен быть?
И на какой текст переписать? Или ты хочешь поправить?

**Comment by BorodinDK** [comment]
Я уже взялся за эту ветку, как ты и говорил,
давай я лучше доделаю

**Comment by BorodinDK** [comment]
Ты же не делал изменений в своей локальной ветке сегодня?

**Comment by aChudinov** [comment]
Нет, не делал.
Уже есть пуллреквест #103, так что вноси правки и давай сливать! :+1:
