### ISSUE TITLE
Выпадающая панель

### ISSUE THREAD

**Issue by mkholodnyak** [shriming/chat#87]
Сверстать блок выпадающей панели. 
Примеры:
- ![image](https://cloud.githubusercontent.com/assets/2128627/10275814/302b5004-6b53-11e5-92f7-535910ec8e91.png)
- ![image](https://cloud.githubusercontent.com/assets/2128627/10275817/335d2504-6b53-11e5-984c-b3e5696555ef.png)

**Comment by aChudinov** [comment]
Да, нужно для моей задачи #79

**Comment by mkholodnyak** [comment]
Не понадобилось, т.к. в каждой панели всего по одному итему.
