### ISSUE TITLE
Поправить цвет и размер spin

### ISSUE THREAD

**Issue by mkholodnyak** [shriming/chat#90]
Доопределить блок `spin` своей реализацией технологии css.

Сейчас блок желтого цвета (`{ theme:  'islands' }`), было бы круто сделать `#383455` (цвет шапки)

**Comment by aChudinov** [comment]
А размер какой?

**Comment by mkholodnyak** [comment]
`{ size: 's' }` неплохо выглядит.

**Comment by aChudinov** [comment]
Куда именно? В списке сообщений он не пропадет? Слишком там большое пространство

**Comment by mkholodnyak** [comment]
В списках пользователей и каналов точно, в `dialog__history` по вкусу
