### ISSUE TITLE
Добавление нового канала

### ISSUE THREAD

**Issue by mkholodnyak** [shriming/chat#94]
- [x] Добавить возможность добавление нового канала

![image](https://cloud.githubusercontent.com/assets/2128627/10276132/165f5af0-6b56-11e5-9061-996ff69cbc49.png)

Ввод названия нового канала выводить в модальном окне (?).

Кнопку с плюсом можно вынести в отдельный блок, она используется на странице несколько раз.

**Comment by Borodin** [comment]
Модальное окно есть в новом дизайне #95

**Comment by mkholodnyak** [comment]
Closed via #159
