### ISSUE TITLE
Дизайн и верстка модального окна с формой ввода

### ISSUE THREAD

**Issue by mkholodnyak** [shriming/chat#95]
Для реализации некоторый фич нужно модальное окно с формой ввода.

@Borodin нарисуешь прототип?

**Comment by Borodin** [comment]
Нарисовал модальное окно, чтобы самые свежие версии дизайна были у всех, я создал новый репозиторий [github.com/shriming/design](https://github.com/shriming/design)

![shriming](https://cloud.githubusercontent.com/assets/645491/10314625/6945dc90-6c5e-11e5-9923-32ed3b4e1ac2.png)
