### ISSUE TITLE
Оптимизация вывода истории сообщений

### ISSUE THREAD

**Issue by mkholodnyak** [shriming/chat#97]
Сейчас в `dialog__history` выводятся абсолютно все сообщения. 
Из-за этого браузер чуть подвисает во время их вставки.

Мб есть смысл выводить только N последних сообщений?

**Comment by aChudinov** [comment]
За это отвечает параметр `count`, который по-умолчанию равен 100. Я думаю надо как-то оптимизировать рендеринг сообщений.

**Comment by mkholodnyak** [comment]
#98

**Comment by aChudinov** [comment]
Выполнять кеширование пользователя в блоке `Users` при поиске, очищать кеш в методе `fetch`

**Comment by mkholodnyak** [comment]
У меня тоже были мысли про кеширование в других блоках. После лекции расскажу одну идею

**Comment by aChudinov** [comment]
c303de8
